spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/youtube_db
spring.datasource.username=postgres
spring.datasource.password=ваша_пароль_здесь

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=your_super_long_and_extremely_secure_secret_key_v3xtr_2026_clone
jwt.expiration=86400000

spring.main.allow-bean-definition-overriding=true

logging.level.org.springframework.security=DEBUG
logging.level.com.youtube.auth_service=TRACE