spring.application.name=auth-service
server.port=8000

# --- Database (Postgres) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-service
spring.datasource.username=myuser
spring.datasource.password=mypassword

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- JWT ---
jwt.access.secret=your_super_secret_access_token_key_32_characters_long
jwt.refresh.secret=your_super_secret_refresh_token_key_32_characters_long

# --- Kafka Cluster Configuration ---
spring.cloud.stream.kafka.binder.brokers=localhost:9092,localhost:9094
spring.cloud.stream.kafka.binder.defaultBrokerPort=9092

# --- Kafka Bindings (Outbox / StreamBridge) ---
# Настройка выходного канала для StreamBridge
# Имя 'userRegistered-out-0' должно совпадать с тем, что ты пишешь в коде или в базе в поле 'topic'
spring.cloud.stream.bindings.userRegistered-out-0.destination=user-registration-topic
spring.cloud.stream.bindings.userRegistered-out-0.producer.required-groups=auth-group

# Настройка входного канала (для будущего Consumer или тестов)
spring.cloud.stream.bindings.userRegistered-in-0.destination=user-registration-topic
spring.cloud.stream.bindings.userRegistered-in-0.group=auth-group

# --- Dead Letter Queue (DLQ) для Consumer ---
spring.cloud.stream.kafka.bindings.userRegistered-in-0.consumer.enable-dlq=true
spring.cloud.stream.kafka.bindings.userRegistered-in-0.consumer.dlq-name=userRegistered-dlq
spring.cloud.stream.bindings.userRegistered-in-0.consumer.max-attempts=3

# --- Producer Reliability (Idempotence & Acks) ---
# Это гарантирует, что сообщение точно дойдет и не задублируется в Кафке
spring.cloud.stream.kafka.binder.producer-properties.acks=all
spring.cloud.stream.kafka.binder.producer-properties.enable.idempotence=true
spring.cloud.stream.kafka.binder.producer-properties.retries=5
spring.cloud.stream.kafka.binder.producer-properties.delivery.timeout.ms=30000

# --- Kafka Topic Management ---
# Не создаем топики с 1 репликой автоматически
spring.cloud.stream.kafka.binder.auto-add-partitions=true
spring.cloud.stream.kafka.binder.min-partition-count=1

# --- Logging ---
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.security=DEBUG
logging.level.com.youtube.auth_service=TRACE
# Чтобы видеть, как работает наш SKIP LOCKED в логах:
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE